start

title PuKi Lovers Bot

:Crear instancia de productor aleatorio;
:Obtener termino aleatorio;
note right: Puppy o Kittie
:Obtener media; 
note right: Los componentes media pueden ser imágenes o gifs animados

if (¿El media ha sido publicado previamente?) then (sí)
    :Descartar;
    stop
else (no)
    if (¿Aparecen personas?) then (sí)
        :Descartar;
        stop
    else (no)
        :Generar contenido publicación;
        note right: Media, mensaje y etiquetas
        :Publicar en SSMM;
        :Guardar registro media;
        stop
    endif
endif

@enduml