start

title PuKi Lovers Bot

:Obtener media; 
note right: Los componentes media pueden ser imágenes o gifs animados

if (¿El contenido ha sido publicado previamente?) then (sí)
    :Descartar;
    stop
else (no)
    if (¿Aparecen personas?) then (sí)
        :Descartar;
        stop
    else (no)
        :Generar contenido publicación;
        note right: Mensaje aleatorio y Etiquetas
        :Concatenar contenido con media;
        :Publicar en SSMM;
        :Guardar registro media;
        :Notificar publicación;
        stop
    endif
endif

@enduml